<script
	src="${pageContext.request.contextPath}/resources/tution/js/angular/angular.min.js"></script>
	<script
	src="${pageContext.request.contextPath}/resources/tution/js/angular/angular-animate.js"></script>
	<script
	src="${pageContext.request.contextPath}/resources/tution/js/angular/angular-cache.js"></script>
	
	<script src="${pageContext.request.contextPath}/resources/tution/js/jquery.validate.js"></script>
	<script
	src="${pageContext.request.contextPath}/resources/tution/js/angular/angular-module.js"></script>
	<script
	src="${pageContext.request.contextPath}/resources/tution/js/angular/angular-recaptcha.js"></script>
<script
	src="${pageContext.request.contextPath}/resources/tution/js/common.js"></script>
	<script
			src="${pageContext.request.contextPath}/resources/tution/js/main/main.js"></script>
<script
	src="${pageContext.request.contextPath}/resources/tution/js/countrySelect.min.js"></script>
<script
	src="${pageContext.request.contextPath}/resources/tution/js/angular/contactUsCtrl.js"></script>
	<script
	src="${pageContext.request.contextPath}/resources/tution/js/angular/homeCtrl.js"></script>
	<script
	src="${pageContext.request.contextPath}/resources/tution/js/angular/headerCtrl.js"></script>
	<script
	src="${pageContext.request.contextPath}/resources/tution/js/angular/footerCtrl.js"></script>
	<script
	src="${pageContext.request.contextPath}/resources/tution/js/angular/loginCtrl.js"></script>
<script
	src="${pageContext.request.contextPath}/resources/tution/js/angular/angularMainCtrl.js"></script>
